### ISSUE TITLE
Roles are deprecated, parse the role tag instead if supported

### ISSUE THREAD

**Issue by thedrow** [garethr/serf-master#4]
Starting from version 0.4 it is recommended to use dynamic tagging instead of roles.
serf-master should use the role tag instead of the old role feature if it is supported by the current agent.

**Comment by garethr** [comment]
Thanks for reporting the issue, however I'm not sure how this affects the serf-master code.

Currently I get the role from the `SERF_SELF_ROLE` env variable: https://github.com/garethr/serf-master/blob/master/serf_master/__init__.py#L10

I could get this from `SERF_TAG_ROLE` instead but they appear to be the same.
Note that according to the docs at http://www.serfdom.io/docs/agent/event-handlers.html, using -role on the agent is deprecated, but the env var isn't.

Or am I missing something obvious?

**Comment by thedrow** [comment]
The environment variable is related to the -role option. You should first parse the tags and get the role tag. If the role tag doesn't exist use the SERF_SELF_ROLE env variable.

**Comment by garethr** [comment]
But that's not what the documentation says at present, the option is deprecated, the env var isn't. @armon do you have a comment on this?

**Comment by armon** [comment]
@garethr Yeah, its a tricky issue of backwards compatibility. It's not likely we will ever remove the `SERF_SELF_ROLE` tag, but the "new" way forward is the `SERF_TAG_ROLE` variable. They will be the same value anyways.

**Comment by garethr** [comment]
I've added support for both, cheers everyone: https://github.com/garethr/serf-master/commit/367db82013c49849e1a37f57604febb0f64fcd36

**Comment by thedrow** [comment]
Wonderful! Thank you.
